---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkf4t-phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: 104.239.168.94
            - name: PMA_PORT
              value: "30002"
            - name: MYSQL_ROOT_PASSWORD
              value: "Sigma@12345"
---
apiVersion: v1
kind: Service
metadata:
  name: darkf4t-phpmyadmin-svc
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    nodePort: 30003
    port: 80
    targetPort: 80

